# version for our compose.yaml file
version: '3.8'

#   List of my technologies used
services:

#   1st technology MySQL we fix its version to 8.0
  mysql:
    image: 'mysql:8.0'

#     we set our credentials
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DB}'
      - 'MYSQL_PASSWORD=${MYSQL_PASS}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}'
      - 'MYSQL_USER=${MYSQL_USER}'

#     we set our port for our database
    ports:
      - '3307:3306'

#     our storage for container
    volumes:
      - blog_db:/var/lib/mysql

# we declare our storage
volumes:
  blog_db:

# commands
#   To run the container: docker-compose up -d
#   To check status: docker ps
